# Generated by Django 3.2.4 on 2022-10-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20221024_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_to',
        ),
    ]
