# Generated by Django 3.2.4 on 2022-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
